name: CI/CD Pipeline

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install
      
    - name: Check Linting
      run: npm run lint
      
    - name: Run Tests
      run: npm test
      
    - name: Build Staging
      if: github.ref == 'refs/heads/staging'
      run: npm run build:staging
      env:
        REACT_APP_ENV: staging
        REACT_APP_API_URL: ${{ secrets.STAGING_API_URL }}
        REACT_APP_GITHUB_URL: ${{ secrets.REACT_APP_GITHUB_URL }}
        REACT_APP_ENABLE_ANIMATIONS: ${{ secrets.REACT_APP_ENABLE_ANIMATIONS }}
        REACT_APP_DEBUG: true
      
    - name: Build Production
      if: github.ref == 'refs/heads/main'
      run: npm run build:prod
      env:
        REACT_APP_ENV: production
        REACT_APP_API_URL: ${{ secrets.PRODUCTION_API_URL }}
        REACT_APP_GITHUB_URL: ${{ secrets.REACT_APP_GITHUB_URL }}
        REACT_APP_ENABLE_ANIMATIONS: ${{ secrets.REACT_APP_ENABLE_ANIMATIONS }}
        REACT_APP_DEBUG: false
      
    - name: Deploy to GitHub Pages (Staging)
      if: github.ref == 'refs/heads/staging'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages-staging
        folder: build
        clean: true
      
    - name: Deploy to GitHub Pages (Production)
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
        clean: true 